# This is the Compose file for command-line services.
# Anything that doesn't need to be run as part of the main `docker-compose up'
# command should reside in here and be invoked by a helper script.
version: "3.7"
services:
  wp:
    build: ./services/wp-cli
    volumes:
      - ./services/wordpress:/var/www/html:cached
      - type: volume
        source: fs-data
        target: /var/www/html/public/wp-content/uploads
  composer:
    image: composer:2
    volumes:
      - ./services/wordpress:/app:cached
  codacy:
    image: codacy/codacy-analysis-cli:latest
    environment:
      &a1
      CODACY_CODE: $PWD
    command: analyze
    volumes:
      &a2
      - $PWD:$PWD:cached
      - /var/run/docker.sock:/var/run/docker.sock:cached
      - /tmp:/tmp:cached
  phpcs:
    image: codacy/codacy-analysis-cli:latest
    environment: *a1
    command: ""
    volumes: *a2
    entrypoint: /opt/codacy/bin/codacy-analysis-cli analyze -t phpcs
  phpmd:
    image: codacy/codacy-analysis-cli:latest
    environment: *a1
    command: ""
    volumes: *a2
    entrypoint: /opt/codacy/bin/codacy-analysis-cli analyze -t phpmd
  eslint:
    image: codacy/codacy-analysis-cli:latest
    environment: *a1
    command: ""
    volumes: *a2
    entrypoint: /opt/codacy/bin/codacy-analysis-cli analyze -t eslint
  stylelint:
    image: codacy/codacy-analysis-cli:latest
    environment: *a1
    command: ""
    volumes: *a2
    entrypoint: /opt/codacy/bin/codacy-analysis-cli analyze -t stylelint
  gesso:
    build: ./services/wordpress/public/wp-content/themes/gesso
    init: true
    volumes:
      - ./services/wordpress/public/wp-content/themes/gesso/images:/app/images:cached
      - ./services/wordpress/public/wp-content/themes/gesso/js:/app/js:cached
      - ./services/wordpress/public/wp-content/themes/gesso/source:/app/source:cached
      - type: volume
        source: gesso-pattern-lab
        target: /app/pattern-lab
      - type: volume
        source: gesso-css
        target: /app/css
volumes: {}
